## Auto-generated by tools/emit_arch_gd.py from SegmentGenerator.Arch.cs
extends RefCounted
class_name SegmentGeneratorArch

const _MathEx := preload("res://shapeup_core/decomposition/su_math_ex.gd")

enum ArchMode {
	Round,
	Segmental,
	Horseshoe,
	PointedHorseshoe,
	ThreeCentered,
	PseudoThreeCentered,
	PseudoFourCentered,
	Triangular,
	RoundedHorseshoe,
	ThreePointed,
	PointedSegmental,
	Parabolic,
	Inflexed,
	RoundRampant,
	Rampant,
	FourCentered,
	Keyhole,
	ReverseOgee,
	OgeeThreeCentered,
	OgeeFourCentered,
	Oriental,
	RoundTrefoil,
	Shouldered,
	PointedTrefoil,
	Draped,
	DoubleDraped,
	Cinquefoil,
	PointedCinquefoil,
	Multifoil,
	RoundRampantMirrored,
	RampantMirrored
}

static func _snap(p: Vector2, snap: float) -> Vector2:
	if snap == 0.0:
		return p
	return Vector2(roundf(p.x / snap) * snap, roundf(p.y / snap) * snap)

static func _bez_pts(p1: Vector2, p2: Vector2, p3: Vector2, p4: Vector2, detail: int, snap: float) -> Array[Vector2]:
	var pts: Array[Vector2] = []
	var last := Vector2(-INF, -INF)
	for i in range(1, detail):
		var t := float(i) / float(detail)
		var pt := _MathEx.bezier_get_point(p1, p2, p3, p4, t)
		pt = _snap(pt, snap)
		if pt != last:
			pts.append(pt)
			last = pt
	return pts

static func collect_arch_points(gen) -> Array[Vector2]:
	var seg = gen.segment
	var p1: Vector2 = seg.position
	var p4: Vector2 = seg.next.position
	var distance: float = p1.distance_to(p4)
	var normal: Vector2 = (p4 - p1).normalized() * distance
	var scaled_normal := normal * (-1.0 if gen.arch_flipped else 1.0)
	var up: Vector2 = -Vector2(-scaled_normal.y, scaled_normal.x)
	var p2: Vector2
	var p3: Vector2
	var out: Array[Vector2] = []
	var arch_detail: int = gen.arch_detail
	var snap_sz: float = gen.arch_grid_snap_size
	match gen.arch_mode:
		ArchMode.Round:
			p2 = p1 + up * 0.666666
			p3 = p4 + up * 0.666666
			for point in _bez_pts(p1, p2, p3, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Segmental:
			p2 = p1 + up * 0.333333 + normal * 0.125
			p3 = p4 + up * 0.333333 - normal * 0.125
			for point in _bez_pts(p1, p2, p3, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Horseshoe:
			p2 = p1 + up * 0.833333 - normal * 0.08
			p3 = p4 + up * 0.833333 + normal * 0.08
			for point in _bez_pts(p1, p2, p3, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PointedHorseshoe:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.625
			p2 = p1 + up * 0.455 - normal * 0.0455
			p3 = midpoint - up * 0.03 - normal * 0.1
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.455 + normal * 0.0455
			p3 = midpoint - up * 0.03 + normal * 0.1
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.ThreeCentered:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.3125
			p2 = p1 + up * 0.3125
			p3 = midpoint - normal * 0.1
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.3125
			p3 = midpoint + normal * 0.1
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PseudoThreeCentered:
			var left = p1 + up * 0.1875 + normal * 0.1875
			var right = p4 + up * 0.1875 - normal * 0.1875
			p2 = p1 + up * 0.1
			p3 = left - normal * 0.1
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			out.append(_snap(right, snap_sz))
			p2 = p4 + up * 0.1
			p3 = right + normal * 0.1
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PseudoFourCentered:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.25
			var left = p1 + up * 0.15 + normal * 0.1225
			var right = p4 + up * 0.15 - normal * 0.1225
			p2 = p1 + up * 0.08 + normal * 0.005
			p3 = left - normal * 0.07 - up * 0.025
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			out.append(_snap(midpoint, snap_sz))
			out.append(_snap(right, snap_sz))
			p2 = p4 + up * 0.08 - normal * 0.005
			p3 = right + normal * 0.07 - up * 0.025
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Triangular:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.5
			out.append(_snap(midpoint, snap_sz))
		ArchMode.RoundedHorseshoe:
			var midpoint = ((p1 + p4) * 0.5) + up * 1.1875
			p2 = p1 + up * 0.52 - normal * 0.4405
			p3 = midpoint - normal * 0.5375
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.52 + normal * 0.4405
			p3 = midpoint + normal * 0.5375
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.ThreePointed:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.75
			p2 = p1 + up * 0.2
			p3 = p1 + up * 0.6 + normal * 0.15
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.2
			p3 = p4 + up * 0.6 - normal * 0.15
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PointedSegmental:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.3125
			p2 = p1 + up * 0.1 + normal * 0.1
			p3 = p1 + up * 0.25 + normal * 0.35
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.1 - normal * 0.1
			p3 = p4 + up * 0.25 - normal * 0.35
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Parabolic:
			var midpoint = ((p1 + p4) * 0.5) + up * 1.375
			p2 = p1 + up * 0.5
			p3 = p1 + up * 1.35 + normal * 0.2
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.5
			p3 = p4 + up * 1.35 - normal * 0.2
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Inflexed:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.375
			p2 = p1 + normal * 0.25
			p3 = p1 + up * 0.15 + normal * 0.45
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 - normal * 0.25
			p3 = p4 + up * 0.15 - normal * 0.45
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.RoundRampant:
			var right = p4 + up * 0.31
			p2 = p1 + up * 0.75 + normal * 0.05
			p3 = p4 + up * 0.8
			for point in _bez_pts(p1, p2, p3, right, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right, snap_sz))
		ArchMode.Rampant:
			var midpoint = ((p1 + p4) * 0.5) + normal * 0.125 + up * 0.9375
			var right = p4 + up * 0.45
			p2 = p1 + up * 0.5
			p3 = p1 + up * 0.85 + normal * 0.35
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.65
			p3 = p4 + up * 0.85 - normal * 0.1
			for point in _bez_pts(midpoint, p3, p2, right, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right, snap_sz))
		ArchMode.FourCentered:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.375
			p2 = p1 + up * 0.25
			p3 = p1 + up * 0.375 + normal * 0.35
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.25
			p3 = p4 + up * 0.375 - normal * 0.35
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Keyhole:
			var right = p1 + up * 0.25 + normal * 0.125
			var left = p4 + up * 0.25 - normal * 0.125
			p2 = p1 + up * 0.055
			p3 = p1 + up * 0.167 + normal * 0.055
			for point in _bez_pts(p1, p2, p3, right, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right, snap_sz))
			var midpoint = ((p1 + p4) * 0.5) + up * 1.125
			p2 = p1 + up * 0.555 - normal * 0.222
			p3 = midpoint - normal * 0.5
			for point in _bez_pts(right, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.555 + normal * 0.222
			p3 = midpoint + normal * 0.5
			for point in _bez_pts(midpoint, p3, p2, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			p2 = p4 + up * 0.055
			p3 = p4 + up * 0.167 - normal * 0.055
			for point in _bez_pts(left, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.ReverseOgee:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.3125
			p2 = p1 + normal * 0.25
			p3 = p1 + up * 0.3 + normal * 0.125
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 - normal * 0.25
			p3 = p4 + up * 0.3 - normal * 0.125
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.OgeeThreeCentered:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.75
			p2 = p1 + up * 0.45 + normal * 0.05
			p3 = p1 + up * 0.3 + normal * 0.3
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.45 - normal * 0.05
			p3 = p4 + up * 0.3 - normal * 0.3
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.OgeeFourCentered:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.4375
			p2 = p1 + up * 0.3 + normal * 0.05
			p3 = p1 + up * 0.25 + normal * 0.3
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.3 - normal * 0.05
			p3 = p4 + up * 0.25 - normal * 0.3
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Oriental:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.75
			p2 = p1 + up * 0.31 - normal * 0.25
			p3 = p1 + up * 0.437 + normal * 0.0625
			for point in _bez_pts(p1, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.31 + normal * 0.25
			p3 = p4 + up * 0.437 - normal * 0.0625
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.RoundTrefoil:
			var left = p1 + up * 0.25 + normal * 0.25
			var right = p4 + up * 0.25 - normal * 0.25
			p2 = p1 + up * 0.13
			p3 = p1 + up * 0.25 + normal * 0.132
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			p2 = left + up * 0.333333 - normal * 0.0265
			p3 = right + up * 0.333333 + normal * 0.0265
			for point in _bez_pts(left, p2, p3, right, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right, snap_sz))
			p2 = p4 + up * 0.13
			p3 = p4 + up * 0.25 - normal * 0.132
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Shouldered:
			var left = p1 + up * 0.25 + normal * 0.25
			var right = p4 + up * 0.25 - normal * 0.25
			p2 = p1 + up * 0.13
			p3 = p1 + up * 0.25 + normal * 0.132
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			var shoulderLeft = p1 + up * 0.375 + normal * 0.25
			var shoulderRight = p4 + up * 0.375 - normal * 0.25
			out.append(_snap(shoulderLeft, snap_sz))
			out.append(_snap(shoulderRight, snap_sz))
			out.append(_snap(right, snap_sz))
			p2 = p4 + up * 0.13
			p3 = p4 + up * 0.25 - normal * 0.132
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PointedTrefoil:
			var midpoint = ((p1 + p4) * 0.5) + up * 0.75
			var left = p1 + up * 0.3125 + normal * 0.3125
			var right = p4 + up * 0.3125 - normal * 0.3125
			p2 = p1 + up * 0.2
			p3 = p1 + up * 0.3125 + normal * 0.1
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			p2 = left + up * 0.15 - normal * 0.1
			p3 = left + up * 0.3125 + normal * 0.05
			for point in _bez_pts(left, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = right + up * 0.15 + normal * 0.1
			p3 = right + up * 0.3125 - normal * 0.05
			for point in _bez_pts(midpoint, p3, p2, right, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right, snap_sz))
			p2 = p4 + up * 0.2
			p3 = p4 + up * 0.3125 - normal * 0.1
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Draped:
			var left = p1 + up * 0.3125 + normal * 0.3125
			var right = p4 + up * 0.3125 - normal * 0.3125
			p2 = p1 + normal * 0.2
			p3 = p1 + up * 0.1 + normal * 0.3125
			for point in _bez_pts(p1, p2, p3, left, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left, snap_sz))
			out.append(_snap(right, snap_sz))
			p2 = p4 - normal * 0.2
			p3 = p4 + up * 0.1 - normal * 0.3125
			for point in _bez_pts(right, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.DoubleDraped:
			var left1 = p1 + up * 0.1875 + normal * 0.1875
			var left2 = p1 + up * 0.375 + normal * 0.375
			var right1 = p4 + up * 0.1875 - normal * 0.1875
			var right2 = p4 + up * 0.375 - normal * 0.375
			p2 = p1 + normal * 0.15
			p3 = p1 + up * 0.05 + normal * 0.1875
			for point in _bez_pts(p1, p2, p3, left1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left1, snap_sz))
			p2 = left1 + normal * 0.125
			p3 = left1 + up * 0.05 + normal * 0.175
			for point in _bez_pts(left1, p2, p3, left2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left2, snap_sz))
			out.append(_snap(right2, snap_sz))
			p2 = right1 - normal * 0.125
			p3 = right1 + up * 0.05 - normal * 0.175
			for point in _bez_pts(right2, p3, p2, right1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right1, snap_sz))
			p2 = p4 - normal * 0.15
			p3 = p4 + up * 0.05 - normal * 0.1875
			for point in _bez_pts(right1, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Cinquefoil:
			var left1 = p1 + up * 0.15625 + normal * 0.125
			var left2 = p1 + up * 0.375 + normal * 0.34375
			var right1 = p4 + up * 0.15625 - normal * 0.125
			var right2 = p4 + up * 0.375 - normal * 0.34375
			p2 = p1 + up * 0.075
			p3 = p1 + up * 0.15 + normal * 0.05
			for point in _bez_pts(p1, p2, p3, left1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left1, snap_sz))
			p2 = left1 + up * 0.15 - normal * 0.075
			p3 = left1 + up * 0.3 + normal * 0.05
			for point in _bez_pts(left1, p2, p3, left2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left2, snap_sz))
			p2 = left2 + up * 0.166666 + normal * 0.075
			p3 = right2 + up * 0.166666 - normal * 0.075
			for point in _bez_pts(left2, p2, p3, right2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right2, snap_sz))
			p2 = right1 + up * 0.15 + normal * 0.075
			p3 = right1 + up * 0.3 - normal * 0.05
			for point in _bez_pts(right2, p3, p2, right1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right1, snap_sz))
			p2 = p4 + up * 0.075
			p3 = p4 + up * 0.15 - normal * 0.05
			for point in _bez_pts(right1, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.PointedCinquefoil:
			var left1 = p1 + up * 0.125 + normal * 0.125
			var left2 = p1 + up * 0.3125 + normal * 0.3125
			var midpoint = ((p1 + p4) * 0.5) + up * 0.5625
			var right1 = p4 + up * 0.125 - normal * 0.125
			var right2 = p4 + up * 0.3125 - normal * 0.3125
			p2 = p1 + up * 0.05
			p3 = p1 + up * 0.125 + normal * 0.075
			for point in _bez_pts(p1, p2, p3, left1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left1, snap_sz))
			p2 = left1 + up * 0.125 - normal * 0.075
			p3 = left1 + up * 0.275 + normal * 0.0125
			for point in _bez_pts(left1, p2, p3, left2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left2, snap_sz))
			p2 = left2 + up * 0.1
			p3 = right2 + up * 0.225 - normal * 0.25
			for point in _bez_pts(left2, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = right2 + up * 0.1
			p3 = left2 + up * 0.225 + normal * 0.25
			for point in _bez_pts(midpoint, p3, p2, right2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right2, snap_sz))
			p2 = right1 + up * 0.125 + normal * 0.075
			p3 = right1 + up * 0.275 - normal * 0.0125
			for point in _bez_pts(right2, p3, p2, right1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right1, snap_sz))
			p2 = p4 + up * 0.05
			p3 = p4 + up * 0.125 - normal * 0.075
			for point in _bez_pts(right1, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.Multifoil:
			var left1 = p1 + up * 0.125 + normal * 0.09375
			var left2 = p1 + up * 0.34375 + normal * 0.1875
			var left3 = p1 + up * 0.53125 + normal * 0.375
			var right1 = p4 + up * 0.125 - normal * 0.09375
			var right2 = p4 + up * 0.34375 - normal * 0.1875
			var right3 = p4 + up * 0.53125 - normal * 0.375
			p2 = p1 + up * 0.05
			p3 = p1 + up * 0.125 + normal * 0.05
			for point in _bez_pts(p1, p2, p3, left1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left1, snap_sz))
			p2 = left1 + up * 0.075 - normal * 0.075
			p3 = left1 + up * 0.225 - normal * 0.05
			for point in _bez_pts(left1, p2, p3, left2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left2, snap_sz))
			p2 = left2 + up * 0.125 - normal * 0.05
			p3 = left2 + up * 0.225 + normal * 0.05
			for point in _bez_pts(left2, p2, p3, left3, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(left3, snap_sz))
			p2 = left3 + up * 0.166666 + normal * 0.025
			p3 = right3 + up * 0.166666 - normal * 0.025
			for point in _bez_pts(left3, p2, p3, right3, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right3, snap_sz))
			p2 = right2 + up * 0.125 + normal * 0.05
			p3 = right2 + up * 0.225 - normal * 0.05
			for point in _bez_pts(right3, p3, p2, right2, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right2, snap_sz))
			p2 = right1 + up * 0.075 + normal * 0.075
			p3 = right1 + up * 0.225 + normal * 0.05
			for point in _bez_pts(right2, p3, p2, right1, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(right1, snap_sz))
			p2 = p4 + up * 0.05
			p3 = p4 + up * 0.125 - normal * 0.05
			for point in _bez_pts(right1, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.RoundRampantMirrored:
			var left = p1 + up * 0.31
			out.append(_snap(left, snap_sz))
			p2 = p4 + up * 0.75 - normal * 0.05
			p3 = p1 + up * 0.8
			for point in _bez_pts(left, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		ArchMode.RampantMirrored:
			var midpoint = ((p1 + p4) * 0.5) - normal * 0.125 + up * 0.9375
			var left = p1 + up * 0.45
			out.append(_snap(left, snap_sz))
			p2 = p1 + up * 0.65
			p3 = p1 + up * 0.85 + normal * 0.1
			for point in _bez_pts(left, p2, p3, midpoint, arch_detail, snap_sz):
				out.append(point)
			out.append(_snap(midpoint, snap_sz))
			p2 = p4 + up * 0.5
			p3 = p4 + up * 0.85 - normal * 0.35
			for point in _bez_pts(midpoint, p3, p2, p4, arch_detail, snap_sz):
				out.append(point)
		_:
			pass
	return out
