## Optional explicit preload chain for Poly2Tri / Delaunay (dependency order).
## Preload this script if you need deterministic parse order before using class_name types.
extends RefCounted

const _TriangulationOrientation := preload("res://shapeup_core/decomposition/delaunay/orientation.gd")
const _TriangulationModeKind := preload("res://shapeup_core/decomposition/delaunay/triangulation_mode.gd")
const _TriangulationPoint := preload("res://shapeup_core/decomposition/delaunay/triangulation_point.gd")
const _TriangulationConstraint := preload("res://shapeup_core/decomposition/delaunay/triangulation_constraint.gd")
const _DTSweepConstraint := preload("res://shapeup_core/decomposition/delaunay/dt_sweep_constraint.gd")
const _TriangulationUtil := preload("res://shapeup_core/decomposition/delaunay/triangulation_util.gd")
const _FixedArray3 := preload("res://shapeup_core/decomposition/delaunay/fixed_array3.gd")
const _DelaunayTriangle := preload("res://shapeup_core/decomposition/delaunay/delaunay_triangle.gd")
const _TriangulatableBase := preload("res://shapeup_core/decomposition/delaunay/triangulatable.gd")
const _TriangulationContext := preload("res://shapeup_core/decomposition/delaunay/triangulation_context.gd")
const _PolygonPoint := preload("res://shapeup_core/decomposition/delaunay/polygon_point.gd")
const _DelaunayPolygon := preload("res://shapeup_core/decomposition/delaunay/delaunay_polygon.gd")
const _DelaunayPointSet := preload("res://shapeup_core/decomposition/delaunay/point_set.gd")
const _ConstrainedPointSet := preload("res://shapeup_core/decomposition/delaunay/constrained_point_set.gd")
const _DelaunayPolygonSet := preload("res://shapeup_core/decomposition/delaunay/polygon_set.gd")
const _AdvancingFrontNode := preload("res://shapeup_core/decomposition/delaunay/advancing_front_node.gd")
const _AdvancingFront := preload("res://shapeup_core/decomposition/delaunay/advancing_front.gd")
const _DTSweepPointComparator := preload("res://shapeup_core/decomposition/delaunay/dt_sweep_point_comparator.gd")
const _DTSweepContext := preload("res://shapeup_core/decomposition/delaunay/dt_sweep_context.gd")
const _DTSweep := preload("res://shapeup_core/decomposition/delaunay/dt_sweep.gd")
const _DelaunayPointGenerator := preload("res://shapeup_core/decomposition/delaunay/point_generator.gd")
const _DelaunayPolygonGenerator := preload("res://shapeup_core/decomposition/delaunay/polygon_generator.gd")
const _EditorVertex := preload("res://shapeup_core/decomposition/editor_vertex.gd")
const _EditorPolygon := preload("res://shapeup_core/decomposition/editor_polygon.gd")
const _DelaunayDecomposer := preload("res://shapeup_core/decomposition/delaunay_decomposer.gd")
