# Generate shapeup_core/shape_editor/segment_generator_arch.gd from SegmentGenerator.Arch.cs
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CS = ROOT / "ShapeUp.Core/ShapeEditor/Generators/SegmentGenerator.Arch.cs"
OUT = ROOT / "shapeup_core/shape_editor/segment_generator_arch.gd"


def main() -> None:
    text = CS.read_text(encoding="utf-8")
    en = re.search(r"public enum ArchMode\s*\{([^}]+)\}", text, re.S)
    assert en
    modes = [ln.strip().rstrip(",") for ln in en.group(1).splitlines() if ln.strip() and not ln.strip().startswith("//")]

    sw = re.search(
        r"switch \(archMode\)\s*\{(.*)\}\s*\n\s*private IEnumerable<float2> Arch_ForEachBezierSegmentPoint",
        text,
        re.S,
    )
    assert sw
    inner = sw.group(1)

    lines = inner.splitlines()
    gd: list[str] = []
    gd.append("## Auto-generated by tools/emit_arch_gd.py from SegmentGenerator.Arch.cs")
    gd.append("extends RefCounted")
    gd.append("class_name SegmentGeneratorArch")
    gd.append("")
    gd.append("enum ArchMode {")
    for i, m in enumerate(modes):
        gd.append(f"\t{m}," if i < len(modes) - 1 else f"\t{m}")
    gd.append("}")
    gd.append("")
    gd.append("static func _snap(p: Vector2, snap: float) -> Vector2:")
    gd.append("\tif snap == 0.0:")
    gd.append("\t\treturn p")
    gd.append("\treturn Vector2(roundf(p.x / snap) * snap, roundf(p.y / snap) * snap)")
    gd.append("")
    gd.append("static func _bez_pts(p1: Vector2, p2: Vector2, p3: Vector2, p4: Vector2, detail: int, snap: float) -> Array[Vector2]:")
    gd.append("\tvar pts: Array[Vector2] = []")
    gd.append("\tvar last := Vector2(-INF, -INF)")
    gd.append("\tfor i in range(1, detail):")
    gd.append("\t\tvar t := float(i) / float(detail)")
    gd.append("\t\tvar pt := MathEx.bezier_get_point(p1, p2, p3, p4, t)")
    gd.append("\t\tpt = _snap(pt, snap)")
    gd.append("\t\tif pt != last:")
    gd.append("\t\t\tpts.append(pt)")
    gd.append("\t\t\tlast = pt")
    gd.append("\treturn pts")
    gd.append("")
    gd.append("static func collect_arch_points(gen) -> Array[Vector2]:")
    gd.append("\tvar seg = gen.segment")
    gd.append("\tvar p1: Vector2 = seg.position")
    gd.append("\tvar p4: Vector2 = seg.next.position")
    gd.append("\tvar distance: float = p1.distance_to(p4)")
    gd.append("\tvar normal: Vector2 = (p4 - p1).normalized() * distance")
    gd.append("\tvar scaled_normal := normal * (-1.0 if gen.arch_flipped else 1.0)")
    gd.append("\tvar up: Vector2 = -Vector2(-scaled_normal.y, scaled_normal.x)")
    gd.append("\tvar p2: Vector2")
    gd.append("\tvar p3: Vector2")
    gd.append("\tvar out: Array[Vector2] = []")
    gd.append("\tvar arch_detail: int = gen.arch_detail")
    gd.append("\tvar snap_sz: float = gen.arch_grid_snap_size")
    gd.append("\tmatch gen.arch_mode:")

    i = 0
    while i < len(lines):
        raw = lines[i].rstrip()
        i += 1
        m = re.match(r"\s*case ArchMode\.(\w+):\s*$", raw)
        if m:
            gd.append(f"\t\tArchMode.{m.group(1)}:")
            continue
        if re.match(r"\s*break;\s*$", raw):
            continue
        if raw.strip() in ("{", "}"):
            continue
        s = raw
        if not s.strip():
            continue
        # strip leading tabs from C#
        indent = "\t\t\t"
        s = s.strip()
        # C# foreach bezier
        if s.startswith("foreach (var point in Arch_ForEachBezierSegmentPoint("):
            inner_call = s[len("foreach (var point in Arch_ForEachBezierSegmentPoint(") :].rstrip("))")
            gd.append(f"{indent}for point in _bez_pts({inner_call}, arch_detail, snap_sz):")
            gd.append(f"{indent}\tout.append(point)")
            continue
        # yield return ... Snap
        ym = re.match(r"yield return (.+)\.Snap\(archGridSnapSize\);", s)
        if ym:
            gd.append(f"{indent}out.append(_snap({ym.group(1)}, snap_sz))")
            continue
        ym2 = re.match(r"yield return (.+);", s)
        if ym2:
            gd.append(f"{indent}out.append({ym2.group(1)})")
            continue
        # var declarations: float2 -> Vector2, math ops
        s = s.replace("float2", "Vector2")
        s = re.sub(r"\(\(p1 \+ p4\) / 2f\)", "((p1 + p4) * 0.5)", s)
        s = re.sub(r"math\.distance\(", "(", s)  # remove wrong
        s = s.replace("math.normalize(", "(")
        s = s.replace("math.lerp(", "lerpf(")
        # fix accidental "(p1" from distance - restore p1.distance_to
        s = re.sub(r"^\(\s*p1\s*,\s*p4\)", "(p1.distance_to(p4))", s)
        # actually line was "var distance = math.distance(p1, p4);" already removed in collect - not in case body
        gd.append(f"{indent}{s}")

    gd.append("\t\t_:")
    gd.append("\t\t\tpass")
    gd.append("\treturn out")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(gd) + "\n", encoding="utf-8")
    print("Wrote", OUT, "lines", len(gd))


if __name__ == "__main__":
    main()
